export default {
  brand: "Noir Salon",
  tagline: "Where style meets precision.",
  location: "Connaught Place, New Delhi",
  phone: "+91 98765 43210",
  instagram: "https://instagram.com/oye.nino",
  accent: "#f59e0b",
  accentSoft: "#fffbeb",
  accentDark: "#b45309",
  theme: "dark",
  slotDuration: 60,
  services: [
    { id: "s1", name: "Haircut + Styling", duration: 60, price: 599 },
    { id: "s2", name: "Beard Trim", duration: 20, price: 199 },
    { id: "s3", name: "Hair Colour", duration: 90, price: 999 },
    { id: "s4", name: "Combo Package", duration: 90, price: 1199 },
  ],
  workingHours: { start: "10:00", end: "20:00" },
  slotIntervalMinutes: 30,
};
